name: Await npm package version
description: "Wait for an npm package version to become available"
branding:
  icon: "clock"
  color: purple
inputs:
  package:
    description: "Name of the npm package"
    required: true
  version:
    description: "Version of the package"
    required: true
  timeout:
    description: "Timeout in seconds"
    required: false
  registry:
    description: "NPM registry to use"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
